// A self-contained HTML page for a whole chart: a density timeline with the
// findings marked, the sensor ring at any moment (scrub or play, notes arrive
// toward their sensor), and the findings list to jump around. All data is
// inlined and nothing is requested from anywhere, so the file works opened
// from a download. The chart's notes are drawn from the parsed data; this page
// never contains the original chart text.
const { slideTracks } = require('./slidePaths');
const { sensorName } = require('./geometry');
const { RULE_NAMES, formatTime } = require('./report');

const round = (n) => Math.round(n * 1000) / 1000;

/** The compact event list the page draws. */
function pageEvents(events) {
    return events.map((e) => {
        if (e.kind === 'slide') {
            const tracks = slideTracks(e);
            return {
                k: 's',
                t: round(e.time),
                a: round(e.start),
                z: round(e.end),
                h: e.head,
                b: e.isBreak ? 1 : 0,
                p: tracks ? tracks.map((track) => track.map((alts) => alts[0])) : [],
            };
        }
        const base = { t: round(e.time) };
        if (e.sensor)
            return {
                ...base,
                k: e.kind === 'touchHold' ? 'th' : 'c',
                n: sensorName(e),
                z: e.end ? round(e.end) : undefined,
            };
        const kind = { tap: 't', break: 'b', hold: 'h' }[e.kind] || 't';
        return {
            ...base,
            k: kind,
            l: e.lane,
            z: e.end ? round(e.end) : undefined,
            st: e.star ? 1 : undefined,
        };
    });
}

const safeJson = (value) =>
    JSON.stringify(value)
        .replace(/</g, '\\u003c')
        .replace(/[\u2028\u2029]/g, '');

function buildViewerHtml({ title, difficulty, events, finish, findings }) {
    const data = {
        title,
        difficulty,
        finish: round(finish),
        events: pageEvents(events),
        findings: findings.map((f) => ({
            r: f.rule,
            n: RULE_NAMES[f.rule] || f.rule,
            s: f.severity,
            bar: f.bar,
            t: round(f.time),
            c: formatTime(f.time),
            x: f.text,
        })),
    };
    return TEMPLATE.replace('__DATA__', () => safeJson(data)).replace(/__TITLE__/g, () =>
        `${title} — ${difficulty}`.replace(/[<>&"]/g, '')
    );
}

const TEMPLATE = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>__TITLE__</title>
<style>
:root{--bg:#fff;--card:#f4f3ee;--ink:#1a1a19;--mute:#6b6a64;--line:#d8d6cc;--s1:#d6a100;--s2:#e8742a;--s3:#d93b3b;--tap:#e0488a;--brk:#f08a24;--hold:#d4a017;--touch:#18a999;--slide:#3b74dd}
@media (prefers-color-scheme:dark){:root{--bg:#1a1a19;--card:#242422;--ink:#fff;--mute:#a09f97;--line:#3a3a36}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 system-ui,"Noto Sans CJK JP",sans-serif}
.wrap{max-width:720px;margin:0 auto;padding:16px}
h1{font-size:22px;margin:0 0 2px}.sub{color:var(--mute);font-size:13px}
.panel{background:var(--card);border-radius:12px;padding:12px;margin-top:12px}
canvas{display:block;width:100%}
.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}
button{font:inherit;background:var(--bg);color:var(--ink);border:1px solid var(--line);border-radius:8px;padding:6px 12px;cursor:pointer}
button.on{background:var(--ink);color:var(--bg)}
input[type=range]{flex:1;min-width:120px}
.chips button{padding:3px 9px;font-size:13px}
.f{display:flex;gap:10px;padding:10px 0;border-top:1px solid var(--line);cursor:pointer}
.f:first-child{border-top:0}.f .sev{flex:none;width:10px;border-radius:5px}
.f .m{color:var(--mute);font-size:12px}.f .t{margin-top:2px}.f.cur{background:rgba(127,127,127,.12)}
.now{font-size:13px;color:var(--mute);min-height:2.6em}
.foot{color:var(--mute);font-size:12px;margin-top:14px}
</style></head><body><div class="wrap">
<h1 id="ttl"></h1><div class="sub" id="sub"></div>
<div class="panel"><canvas id="tl" height="90"></canvas>
<div class="row" style="margin-top:8px"><button id="play">▶ Play</button><button id="prev">◀ Prev</button><button id="next">Next ▶</button>
<button id="spd">1×</button><input id="seek" type="range" min="0" step="0.01"><span id="clock" class="sub"></span></div></div>
<div class="panel"><canvas id="ring" height="380"></canvas><div class="now" id="now"></div></div>
<div class="panel"><div class="row chips" id="chips"></div><div id="list" style="margin-top:6px"></div></div>
<div class="foot">Risks read from a fan transcription of the chart, not certainties; thresholds are not calibrated yet. Slide timing assumes even travel. Generated by Atri.</div>
</div>
<script>
const D=__DATA__;
const $=id=>document.getElementById(id);
$('ttl').textContent=D.title;$('sub').textContent=D.difficulty+' · '+Math.round(D.finish)+'s · '+D.findings.length+' findings';
const css=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const SEV={1:'--s1',2:'--s2',3:'--s3'};
let at=0,playing=false,speed=1,last=0,active=new Set(Object.keys(D.findings.reduce((a,f)=>(a[f.r]=1,a),{})));
const WIN_BEFORE=0.2,WIN_AFTER=0.7;
function xy(name,R,C){if(name==='C')return[C,C];const L=name[0],n=+name.slice(1);const al=(L==='A'||L==='B')?22.5+45*(n-1):45*(n-1);const a=al*Math.PI/180;const r={A:.8,B:.5,D:.97,E:.68}[L]*R;return[C+r*Math.sin(a),C-r*Math.cos(a)]}
function setup(c,h){const dpr=window.devicePixelRatio||1,w=c.clientWidth;c.width=w*dpr;c.height=h*dpr;c.style.height=h+'px';const g=c.getContext('2d');g.scale(dpr,dpr);return[g,w]}
const bins=Math.max(1,Math.ceil(D.finish)),dens=new Array(bins).fill(0);D.events.forEach(e=>{dens[Math.min(bins-1,Math.floor(e.t))]++});const dmax=Math.max(...dens,1);
function drawTL(){const[g,w]=setup($('tl'),90);const h=90;g.clearRect(0,0,w,h);g.fillStyle=css('--line');
 dens.forEach((d,i)=>{const bh=(d/dmax)*(h-26);g.fillRect(i/D.finish*w,h-bh,Math.max(1,w/bins-0.5),bh)});
 D.findings.filter(f=>active.has(f.r)).forEach(f=>{g.fillStyle=css(SEV[f.s]);const x=f.t/D.finish*w;g.fillRect(x-1,2,2,10+f.s*4)});
 g.fillStyle=css('--ink');const x=at/D.finish*w;g.fillRect(x-1,0,2,h)}
function drawRing(){const c=$('ring'),[g,w]=setup(c,Math.min(c.clientWidth,380));const S=Math.min(w,380),C=S/2,R=C-18,ox=(w-S)/2;g.clearRect(0,0,w,S);g.save();g.translate(ox,0);
 g.strokeStyle=css('--line');g.lineWidth=1.5;g.beginPath();g.arc(C,C,R,0,7);g.stroke();
 for(let n=1;n<=8;n++){const[x,y]=xy('A'+n,R,C);g.beginPath();g.arc(x,y,13,0,7);g.stroke();g.fillStyle=css('--mute');g.font='11px sans-serif';g.textAlign='center';g.fillText(n,x,y+4)}
 const col=k=>css(k==='b'?'--brk':k==='h'?'--hold':k==='c'||k==='th'?'--touch':'--tap');
 const prog=t=>Math.max(0,Math.min(1,1-(t-at)/WIN_AFTER));
 D.events.forEach(e=>{if(e.k!=='s')return;if(e.z<at-WIN_BEFORE||e.a>at+WIN_AFTER+0.3)return;const on=at>=e.a-0.05&&at<=e.z+0.05;
  e.p.forEach(path=>{g.strokeStyle=css('--slide');g.globalAlpha=on?.95:.4;g.lineWidth=on?3.5:1.5;g.beginPath();path.forEach((s,i)=>{const[x,y]=xy(s,R,C);i?g.lineTo(x,y):g.moveTo(x,y)});g.stroke();
   if(on&&e.z>e.a){const f=Math.max(0,Math.min(1,(at-e.a)/(e.z-e.a)))*(path.length-1),i=Math.floor(f),[x1,y1]=xy(path[i],R,C),[x2,y2]=xy(path[Math.min(path.length-1,i+1)],R,C),k=f-i;g.globalAlpha=1;g.fillStyle=css('--slide');g.beginPath();g.arc(x1+(x2-x1)*k,y1+(y2-y1)*k,6,0,7);g.fill()}});
  g.globalAlpha=1;const[hx,hy]=xy('A'+e.h,R,C);g.fillStyle=css('--slide');g.font='15px sans-serif';g.textAlign='center';g.fillText('★',hx,hy+5)});
 D.events.forEach(e=>{if(e.k==='s')return;const t1=e.z&&e.z>e.t?e.z:e.t;if(e.t>at+WIN_AFTER||t1<at-WIN_BEFORE)return;
  const p=e.n?xy(e.n,R,C):xy('A'+e.l,R,C),pr=prog(e.t),near=Math.abs(e.t-at)<0.06;g.globalAlpha=near?1:.35+.65*pr;g.fillStyle=col(e.k);
  const rad=(e.n?7:8)+(1-pr)*8*(e.t>at?1:0);
  if(e.n){g.fillRect(p[0]-rad,p[1]-rad,rad*2,rad*2)}else{g.beginPath();g.arc(p[0],p[1],rad,0,7);g.fill()}
  if(e.z&&e.z>e.t&&(e.k==='h'||e.k==='th')&&at>=e.t&&at<=e.z){g.strokeStyle=col(e.k);g.lineWidth=3;g.beginPath();g.arc(p[0],p[1],rad+4,0,7);g.stroke()}
  g.globalAlpha=1;g.fillStyle=css('--mute');g.font='10px sans-serif';g.textAlign='center';if(e.n)g.fillText(e.n,p[0],p[1]-rad-3)});
 g.restore()}
function nowText(){const near=D.findings.filter(f=>active.has(f.r)&&at-0.2<=f.t&&f.t<=at+0.7);$('now').innerHTML=near.length?near.slice(0,3).map(f=>'<b>'+f.r+'</b> '+esc(f.x)).join('<br>'):'';}
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function draw(){$('seek').value=at;$('clock').textContent=Math.floor(at/60)+':'+(at%60).toFixed(1).padStart(4,'0');drawTL();drawRing();nowText();
 document.querySelectorAll('.f').forEach(el=>el.classList.toggle('cur',Math.abs(+el.dataset.t-at)<0.35))}
function go(t){at=Math.max(0,Math.min(D.finish,t));draw()}
function list(){const visible=D.findings.filter(f=>active.has(f.r));$('list').innerHTML=visible.map(f=>'<div class="f" data-t="'+f.t+'"><div class="sev" style="background:'+css(SEV[f.s])+'"></div><div><div class="m">'+f.r+' · '+esc(f.n)+' · bar '+f.bar+' · '+f.c+'</div><div class="t">'+esc(f.x)+'</div></div></div>').join('')||'<div class="sub">Nothing flagged.</div>';
 document.querySelectorAll('.f').forEach(el=>el.onclick=()=>{go(+el.dataset.t-0.25)})}
const rules=[...new Set(D.findings.map(f=>f.r))].sort();
$('chips').innerHTML=rules.map(r=>'<button class="on" data-r="'+r+'">'+r+'</button>').join('');
document.querySelectorAll('#chips button').forEach(b=>b.onclick=()=>{active.has(b.dataset.r)?active.delete(b.dataset.r):active.add(b.dataset.r);b.classList.toggle('on');list();draw()});
$('seek').max=D.finish;$('seek').oninput=e=>go(+e.target.value);
$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'⏸ Pause':'▶ Play';last=0;if(playing)requestAnimationFrame(tick)};
$('spd').onclick=()=>{speed=speed===1?.5:speed===.5?.25:1;$('spd').textContent=speed+'×'};
function jump(d){const v=D.findings.filter(f=>active.has(f.r)).map(f=>f.t-0.25);const t=d>0?v.find(x=>x>at+0.05):[...v].reverse().find(x=>x<at-0.05);if(t!==undefined)go(t)}
$('next').onclick=()=>jump(1);$('prev').onclick=()=>jump(-1);
$('tl').onclick=e=>go((e.offsetX/e.target.clientWidth)*D.finish);
function tick(ts){if(!playing)return;if(last)at=Math.min(D.finish,at+(ts-last)/1000*speed);last=ts;draw();if(at>=D.finish){playing=false;$('play').textContent='▶ Play'}else requestAnimationFrame(tick)}
addEventListener('resize',draw);list();go(D.findings.length?Math.max(0,D.findings.find(f=>f.s===3)?.t-0.25||0):0);
</script></body></html>`;

module.exports = { buildViewerHtml };
