// HTML -> PNG, for the image cards (B50, rating history). Uses the bot's
// existing resident Chromium (web/playwrightFetcher.js), so there is still
// only one browser process, and it closes itself when idle.
const { getBrowser, scheduleIdleClose } = require('../web/playwrightFetcher');
const logger = require('../utils/logger');

const MAX_CONCURRENT = 2;
const RENDER_TIMEOUT_MS = 25000;

let running = 0;
const waiting = [];

/** At most MAX_CONCURRENT renders at once: a card is a few hundred MB of Chromium page, and the host is small. */
async function acquire() {
    if (running < MAX_CONCURRENT) {
        running++;
        return;
    }
    await new Promise((resolve) => waiting.push(resolve));
}

function release() {
    const next = waiting.shift();
    if (next)
        next(); // hand the slot straight over
    else running--;
}

/**
 * Renders `html` and returns a PNG Buffer of the whole page.
 *
 * The HTML is generated by us from external data (song titles, friend names),
 * so the page can only load what it needs: `allowedHosts` (the cover CDN) and
 * inline data. Anything else — a stray <img src> in a title that slipped
 * through escaping, say — is aborted rather than fetched.
 *
 * @param {string} html
 * @param {{width: number, scale?: number, allowedHosts?: string[]}} options
 */
async function renderHtmlToPng(html, { width, scale = 2, allowedHosts = [] }) {
    await acquire();
    let context;
    try {
        const browser = await getBrowser();
        context = await browser.newContext({
            // Short on purpose: a fullPage screenshot is at least as tall as the viewport,
            // so a tall one left dead space under short cards.
            viewport: { width, height: 100 },
            deviceScaleFactor: scale,
        });
        const page = await context.newPage();
        page.setDefaultTimeout(RENDER_TIMEOUT_MS);

        await page.route('**/*', async (route) => {
            const url = route.request().url();
            let allowed = url.startsWith('data:') || url === 'about:blank';
            if (!allowed) {
                try {
                    allowed = allowedHosts.includes(new URL(url).hostname);
                } catch {
                    allowed = false;
                }
            }
            if (allowed) await route.continue();
            else await route.abort();
        });

        // 'networkidle' waits for the cover art; a cover that fails just leaves
        // its placeholder (templates hide a broken <img>), it doesn't fail the card.
        await page.setContent(html, { waitUntil: 'networkidle', timeout: RENDER_TIMEOUT_MS });
        await page.evaluate(() => document.fonts.ready);
        return await page.screenshot({ type: 'png', fullPage: true });
    } catch (err) {
        logger.error('render', 'Could not render an image', err);
        throw new Error(`Could not render the image: ${err.message}`);
    } finally {
        if (context) await context.close().catch(() => {});
        scheduleIdleClose();
        release();
    }
}

module.exports = { renderHtmlToPng };
