// Circle rankings: horizontal bars, points labelled at the tip. Points are a
// true quantity with a meaningful zero, so bar length is honest here (unlike
// ratings; see leaderboardCard.js). Built to the dataviz spec: one series in
// one colour, bars <= 24px with a 4px rounded data end and a square baseline,
// no legend, no gridlines — every bar carries its own value. Pure.
const { TOKENS, BASE_CSS, escapeHtml, displayName, formatInt } = require('./theme');

const WIDTH = 1000;

const CSS = `
${BASE_CSS}
.card { width: ${WIDTH}px; padding: 32px; }
.label { color: ${TOKENS.inkMuted}; font-size: 13px; font-weight: 600; letter-spacing: 0.08em; text-transform: uppercase; }
.title { font-size: 40px; font-weight: 700; line-height: 1.1; margin-top: 6px; }
.sub { color: ${TOKENS.inkSecondary}; font-size: 16px; margin-top: 8px; }
.rows { margin-top: 24px; }
.row { display: flex; align-items: center; height: 34px; }
.rank { width: 44px; text-align: right; padding-right: 12px; color: ${TOKENS.inkMuted}; font-size: 14px; }
.name { width: 300px; font-size: 15px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; padding-right: 14px; }
.track { position: relative; flex: 1; height: 18px; margin-right: 86px; }
.bar { height: 18px; background: ${TOKENS.series1}; border-radius: 0 4px 4px 0; min-width: 2px; position: relative; }
.value { position: absolute; left: 100%; top: 50%; transform: translateY(-50%); padding-left: 8px; font-size: 14px; font-weight: 600; white-space: nowrap; }
.footer { margin-top: 20px; color: ${TOKENS.inkMuted}; font-size: 12px; text-align: right; }
`;

/**
 * @param {object} model
 * @param {string|null} model.scrapedAt   readable
 * @param {Array<{rank:number,groupName:string,points:number}>} model.rankings  best first
 */
function buildCircleHtml({ scrapedAt, rankings }) {
    const max = Math.max(...rankings.map((r) => r.points), 1);
    const rows = rankings
        .map(
            (r) =>
                `<div class="row"><div class="rank tabular">${escapeHtml(r.rank)}</div><div class="name">${escapeHtml(displayName(r.groupName))}</div><div class="track"><div class="bar" style="width:${((r.points / max) * 100).toFixed(2)}%"><span class="value tabular">${formatInt(r.points)}</span></div></div></div>`
        )
        .join('');
    return `<!doctype html><html><head><meta charset="utf-8"><style>${CSS}</style></head><body>
<div class="card">
  <div class="label">Circle rankings</div>
  <div class="title">Points by circle</div>
  <div class="sub">Top ${rankings.length} · scraped ${escapeHtml(scrapedAt || '–')}</div>
  <div class="rows">${rows}</div>
  <div class="footer">Bars start at zero. Generated by Atri</div>
</div>
</body></html>`;
}

module.exports = { buildCircleHtml, WIDTH };
