// "Scores by level": the best score at each constant of one displayed level,
// with the cover, difficulty, rank, AP/FC badge and how many of that
// constant's charts have been played. This is the long per-constant table
// that used to run into the output-token cap as text. Pure: data in, HTML out.
const { TOKENS, BASE_CSS, escapeHtml, coverUrl } = require('./theme');
const { DIFFICULTIES } = require('./b50Card');
const { getRankByAchievement } = require('../web/maimaiRatingMath');

const WIDTH = 1100;

const CSS = `
${BASE_CSS}
.card { width: ${WIDTH}px; padding: 32px; }
.label { color: ${TOKENS.inkMuted}; font-size: 13px; font-weight: 600; letter-spacing: 0.08em; text-transform: uppercase; }
.hero { font-size: 72px; font-weight: 700; line-height: 1; margin-top: 6px; }
.sub { color: ${TOKENS.inkSecondary}; font-size: 16px; margin-top: 10px; }
.rows { margin-top: 24px; display: flex; flex-direction: column; gap: 8px; }
.row { display: flex; align-items: center; gap: 16px; height: 64px; padding: 8px 16px 8px 8px; background: ${TOKENS.raised}; border-radius: 8px; }
.row.empty { background: transparent; border: 1px dashed ${TOKENS.axis}; }
.const { width: 74px; text-align: center; font-size: 26px; font-weight: 700; }
.cover { flex: 0 0 48px; width: 48px; height: 48px; border-radius: 6px; background: ${TOKENS.axis}; overflow: hidden; }
.cover img { display: block; width: 48px; height: 48px; object-fit: cover; }
.song { flex: 1; min-width: 0; }
.song .title { font-size: 16px; font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.song .meta { margin-top: 4px; display: flex; align-items: center; gap: 6px; }
.pill { padding: 1px 7px; border-radius: 4px; color: #111; font-size: 12px; font-weight: 700; }
.tag { color: ${TOKENS.inkMuted}; font-size: 11px; font-weight: 600; }
.achv { width: 120px; text-align: right; font-size: 21px; font-weight: 700; }
.rank { width: 56px; color: ${TOKENS.inkSecondary}; font-size: 15px; font-weight: 600; }
.badge { width: 52px; text-align: center; }
.badge span { display: inline-block; padding: 1px 8px; border: 1px solid ${TOKENS.inkMuted}; border-radius: 4px; color: ${TOKENS.ink}; font-size: 12px; font-weight: 700; }
.played { width: 118px; text-align: right; color: ${TOKENS.inkMuted}; font-size: 14px; }
.none { flex: 1; color: ${TOKENS.inkMuted}; font-size: 15px; }
.footer { margin-top: 20px; color: ${TOKENS.inkMuted}; font-size: 12px; text-align: right; }
`;

/**
 * @param {object} model
 * @param {string} model.level          the displayed level, e.g. "14+"
 * @param {number} model.totalCharts
 * @param {number} model.playedCharts
 * @param {Array<{constant:number, played:number, total:number, best:null|{song,difficulty,chartType,achievement,apFc,cover}}>} model.constants  hardest first
 */
function buildLevelScoresHtml({ level, totalCharts, playedCharts, constants }) {
    const rows = constants
        .map((c) => {
            const played = `<div class="played tabular">${c.played}/${c.total} played</div>`;
            if (!c.best) {
                return `<div class="row empty"><div class="const tabular">${c.constant.toFixed(1)}</div><div class="none">No plays yet at this constant</div>${played}</div>`;
            }
            const b = c.best;
            const diff = DIFFICULTIES[String(b.difficulty || '').toLowerCase()] || {
                label: String(b.difficulty || '?')
                    .slice(0, 4)
                    .toUpperCase(),
                color: TOKENS.inkMuted,
            };
            const cover = coverUrl(b.cover);
            const rank = getRankByAchievement(b.achievement)?.title || '';
            return `<div class="row">
  <div class="const tabular">${c.constant.toFixed(1)}</div>
  <div class="cover">${cover ? `<img src="${escapeHtml(cover)}" onerror="this.style.display='none'">` : ''}</div>
  <div class="song"><div class="title">${escapeHtml(b.song)}</div><div class="meta"><span class="pill" style="background:${diff.color}">${escapeHtml(diff.label)}</span><span class="tag">${b.chartType === 'dx' ? 'DX' : 'STD'}</span></div></div>
  <div class="achv tabular">${b.achievement.toFixed(4)}%</div>
  <div class="rank">${escapeHtml(rank)}</div>
  <div class="badge">${b.apFc ? `<span>${escapeHtml(b.apFc)}</span>` : ''}</div>
  ${played}
</div>`;
        })
        .join('');
    return `<!doctype html><html><head><meta charset="utf-8"><style>${CSS}</style></head><body>
<div class="card">
  <div class="label">Scores by level</div>
  <div class="hero">${escapeHtml(level)}</div>
  <div class="sub">Best score at each constant · ${playedCharts} of ${totalCharts} charts played</div>
  <div class="rows">${rows}</div>
  <div class="footer">Constants from mai-tools · badges read from the game's own icons · Generated by Atri</div>
</div>
</body></html>`;
}

module.exports = { buildLevelScoresHtml, WIDTH };
