// Play history for one song: a row per difficulty with level, plays (a bar from
// zero, so where the plays went is visible at a glance), best achievement,
// rank, clear and sync badges, and when it was last played. Five of the last
// month's questions were exactly this table, in text. Pure.
const { TOKENS, BASE_CSS, escapeHtml, formatInt, coverUrl } = require('./theme');
const { PARTS_CSS, difficultyPill, badgePills } = require('./parts');

const WIDTH = 1000;
const BAR_MAX = 190;

const CSS = `
${BASE_CSS}
${PARTS_CSS}
.card { width: ${WIDTH}px; padding: 32px; }
.top { display: flex; gap: 22px; align-items: center; }
.cover { flex: 0 0 120px; width: 120px; height: 120px; border-radius: 10px; background: ${TOKENS.axis}; overflow: hidden; }
.cover img { display: block; width: 120px; height: 120px; object-fit: cover; }
.label { color: ${TOKENS.inkMuted}; font-size: 13px; font-weight: 600; letter-spacing: 0.08em; text-transform: uppercase; }
.title { font-size: 34px; font-weight: 700; line-height: 1.15; margin-top: 4px; overflow-wrap: anywhere; }
.sub { color: ${TOKENS.inkSecondary}; font-size: 16px; margin-top: 8px; }
.rows { margin-top: 26px; display: flex; flex-direction: column; gap: 8px; }
.head, .row { display: flex; align-items: center; gap: 16px; }
.head { padding: 0 16px; color: ${TOKENS.inkMuted}; font-size: 12px; font-weight: 600; letter-spacing: 0.06em; text-transform: uppercase; }
.row { height: 62px; padding: 8px 16px; background: ${TOKENS.raised}; border-radius: 8px; }
.c-diff { flex: 0 0 96px; }
.c-plays { flex: 0 0 ${BAR_MAX + 70}px; }
.c-best { flex: 0 0 112px; text-align: right; }
.c-rank { flex: 0 0 48px; }
.c-badges { flex: 1; min-width: 0; white-space: nowrap; }
.c-last { flex: 0 0 124px; text-align: right; }
.row .c-last { color: ${TOKENS.inkSecondary}; font-size: 13px; }
.bar { position: relative; height: 18px; background: ${TOKENS.series1}; border-radius: 0 4px 4px 0; min-width: 3px; }
.bar .n { position: absolute; left: 100%; top: 50%; transform: translateY(-50%); padding-left: 8px; font-size: 15px; font-weight: 700; white-space: nowrap; }
.none { color: ${TOKENS.inkMuted}; font-size: 15px; }
.achv { font-size: 20px; font-weight: 700; }
.rank { color: ${TOKENS.inkSecondary}; font-size: 15px; font-weight: 600; }
.stars { color: ${TOKENS.inkSecondary}; font-size: 13px; margin-left: 8px; }
.footer { margin-top: 22px; color: ${TOKENS.inkMuted}; font-size: 12px; text-align: right; }
`;

/**
 * @param {object} model
 * @param {string} model.title
 * @param {string|null} model.artist
 * @param {string|null} model.cover
 * @param {Array<{difficulty, level, plays, best, rank, clear, sync, stars, lastPlayed}>} model.rows  easiest first
 */
function buildPlayHistoryHtml({ title, artist, cover, rows }) {
    const total = rows.reduce((n, r) => n + (r.plays || 0), 0);
    const max = Math.max(...rows.map((r) => r.plays || 0), 1);
    const img = coverUrl(cover, true);
    const body = rows
        .map((r) => {
            const bar = r.plays
                ? `<div class="bar" style="width:${Math.max(3, Math.round((r.plays / max) * BAR_MAX))}px"><span class="n tabular">${formatInt(r.plays)}</span></div>`
                : '<span class="none">–</span>';
            return `<div class="row">
  <div class="c-diff">${difficultyPill(r.difficulty, r.level)}</div>
  <div class="c-plays">${bar}</div>
  <div class="c-best achv tabular">${r.best == null ? '–' : `${r.best.toFixed(4)}%`}</div>
  <div class="c-rank rank">${escapeHtml(r.rank || '')}</div>
  <div class="c-badges">${badgePills(r.clear, r.sync)}${r.stars ? `<span class="stars tabular">★${r.stars}</span>` : ''}</div>
  <div class="c-last tabular">${escapeHtml(r.lastPlayed || '')}</div>
</div>`;
        })
        .join('');
    return `<!doctype html><html><head><meta charset="utf-8"><style>${CSS}</style></head><body>
<div class="card">
  <div class="top">
    <div class="cover">${img ? `<img src="${escapeHtml(img)}" onerror="this.style.display='none'">` : ''}</div>
    <div>
      <div class="label">Your play history</div>
      <div class="title">${escapeHtml(title)}</div>
      <div class="sub">${artist ? `${escapeHtml(artist)} · ` : ''}${formatInt(total)} play${total === 1 ? '' : 's'} across ${rows.length} difficult${rows.length === 1 ? 'y' : 'ies'}</div>
    </div>
  </div>
  <div class="rows">
    <div class="head"><span class="c-diff">Chart</span><span class="c-plays">Plays</span><span class="c-best">Best</span><span class="c-rank">Rank</span><span class="c-badges">Clear</span><span class="c-last">Last played</span></div>
    ${body}
  </div>
  <div class="footer">Bars start at zero · clear badges read from the game's own icons · Generated by Atri</div>
</div>
</body></html>`;
}

module.exports = { buildPlayHistoryHtml, WIDTH };
